# Generated by Django 6.0.5 on 2026-05-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'Truck'), ('Bus', 'Bus'), ('Van', 'Van'), ('Boda', 'Boda'), ('Bajaji', 'Bajaji'), ('Courier Bike', 'Courier Bike')], max_length=50)),
                ('transport_type', models.CharField(choices=[('Freight', 'Freight'), ('Passenger', 'Passenger'), ('Courier', 'Courier'), ('Agriculture', 'Agriculture'), ('General Transport', 'General Transport')], max_length=50)),
                ('main_route', models.CharField(help_text='Primary route e.g. Dar es Salaam → Morogoro', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('estimated_time', models.CharField(default='—', max_length=100)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Caution', 'Caution'), ('High Risk', 'High Risk'), ('Avoid', 'Avoid')], default='Safe', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('incident_type', models.CharField(choices=[('Accident', 'Accident'), ('Flood', 'Flood'), ('Bad Road', 'Bad Road'), ('Traffic Jam', 'Traffic Jam'), ('Road Block', 'Road Block'), ('Police Checkpoint', 'Police Checkpoint'), ('Fuel Shortage', 'Fuel Shortage'), ('Theft Hotspot', 'Theft Hotspot'), ('Vehicle Breakdown', 'Vehicle Breakdown')], max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.transportroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
