# Generated by Django 6.0.5 on 2026-05-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('estimated_time', models.CharField(default='—', max_length=50)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Caution', 'Caution'), ('High Risk', 'High Risk'), ('Avoid', 'Avoid')], default='Safe', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.transportroute')),
            ],
            options={
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Specific road section affected (auto-matched if blank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.routesegment'),
        ),
    ]
