# Generated by Django 6.0.5 on 2026-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routesegment_incidentreport_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='ai_estimated_delay_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ai_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ai_risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
