# Generated by Django 6.0.5 on 2026-05-30 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ussdsession_airtimereward_atsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='trust_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_incidents', to='core.driver'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_driver',
            field=models.ForeignKey(blank=True, help_text='Linked driver account (if reporter was logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='core.driver'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.routesegment'),
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='core.driver')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='core.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('rater', 'rated')},
            },
        ),
    ]
